### ISSUE TITLE
Using Event-Timestamp AVP

### ISSUE THREAD

**Issue by luisfilsilva** [node-diameter/node-diameter#73]
Hi guys,

I'm trying to use the Event-Timestamp AVP with the current time. 

I was trying to use Math.round(new Date().now()/1000) but it doesn't seem to be working. 

Can you tell me how I can pass this value?

Thanks,
Luís

**Comment by luisfilsilva** [comment]
By adding 2208988800, I believe I was able to make it work. Is this the right procedure?

Thanks,
Luís

**Comment by atesgoral** [comment]
Hi @luisfilsilva!

Diameter [defines the Time type](https://tools.ietf.org/html/rfc3588#page-42) as:

> The Time format is derived from the OctetString AVP Base Format.
> The string MUST contain four octets, in the same format as the
> first four bytes are in the NTP timestamp format.  The NTP
> Timestamp format is defined in chapter 3 of [SNTP].
> This represents the number of seconds since 0h on 1 January 1900
> with respect to the Coordinated Universal Time (UTC).

And [in JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date):

> A JavaScript date is fundamentally specified as the number of milliseconds that have elapsed since midnight on January 1, 1970, UTC. This date and time is the same as the UNIX epoch, which is the predominant base value for computer-recorded date and time values.

So the delta between the two epochs can be derived by parsing the [ISO8601 string](https://en.wikipedia.org/wiki/ISO_8601#Coordinated_Universal_Time_(UTC)):

```
Date.parse('1900-01-01T00:00:00Z') / 1000 // -2208988800
```

So, you're right in needing to offset the value yourself, since this library doesn't do a conversion from/to JavaScript Date values.
